from typing import NamedTuple


class Frames(NamedTuple):
    frame_h1: str
    frame_h2: str
    frame_h3: str
    frame_h4: str
    frame_l1: str
    frame_l2: str
    frame_l3: str
    frame_l4: str


# Dict of FRs of all supported libraries
lib_frame_dict = {
    'SH_VH3-23_Vk1-39':
        Frames(
            'GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGA',  # FRH1
            'TGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTC',  # FRH2
            'GACTCCGTGAAGGGCCGGTTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCCGTGTATTACTGT',  # FRH3
            'TGGGGCCAGGGCACCCTGGTCACCGTCTCCTCA',  # FRH4
            'GACATCCAGATGACCCAGTCTCCATCCTCCCTGTCTGCATCTGTAGGAGACCGTGTCACCATCACTTGCCGG',  # FRL1
            'TTAAATTGGTATCAGCAGAAACCAGGGAAAGCCCCTAAGCTCCTGATCTAT',  # FRL2
            'GGGGTCCCATCACGCTTCAGTGGCAGTGGATCTGGGACAGATTTCACTCTCACCATCAGCAGTCTGCAACCTGAAGATTTTGCAACTTACTACTGTCAA',  # FRL3
            'TTCGGCGGAGGTACCAAGGTGGAGATCAAA',  # FRL4
        ),
    }
